excence_blog:
    resource: "@ExcenceBlogBundle/Resources/config/routing.xml"
    prefix:   /excence

wpug_user:
    resource: "@WpugUserBundle/Resources/config/routing.xml"
    prefix:   /

wpug_post:
    resource: "@WpugPostBundle/Resources/config/routing.xml"
    prefix:   /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

