<?php

namespace Wpug\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findByCategory($category) 
    {
        return $this->getEntityManager()->createQueryBuilder()
                ->select('p', 'c')
                ->from('WpugPostBundle:Post', 'p')
                ->join('p.category', 'c')
                ->where('c.id = :category')
                ->where('p.title LIKE :word')
                ->setParameter('word', '%'.$word.'%')
                ->setParameter('category', $category)
                ->getQuery()
                ->getResult();
    }
}
